#!/usr/bin/env bash

OUTPUT_DIR=output

THREADS="1000 1000000 10000000"

NODES="1 2 4 5 8 10 16 20 25 40 50 80 100 125 200 250 400 500 625 1000 1250 2000 2500 5000 10000 "

LOOPS=$(seq 1 10)

OUTPUT_HEADER="build, mode, threads, launches, nodes, iterations, total, cuda_diff, graph_creation, total_launch, exec, results, Memory (MiB)"

OUTPUT_FILE="$OUTPUT_DIR/output_mem.txt"
echo $OUTPUT_HEADER > $OUTPUT_FILE
for T in $THREADS;
do
  for N in $NODES;
  do
    for L in $LOOPS
    do
      ./iterapp -g -t $T -o 1 -i 1 -k $N | sed -z 's/memory.used \[MiB\]\n\([0-9]*\) MiB\n\([^\n]*\)\n/\2, \1\n/g' | tee -a $OUTPUT_FILE
    done
  done
done
